name: mcdocker
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: '>=2.17.0-edge.9df38b50da5f6442f51c903182da7880abc45fca <3.0.0'

dependencies:
  uuid: 3.0.5
  http: ^0.13.4
  args: ^2.0.0
  path: ^1.8.1
  system_info2: ^2.0.3
  archive: ^3.1.11

dev_dependencies:
  lints: ^1.0.0
